### ISSUE TITLE
无法输入中文

### ISSUE THREAD

**Issue by PureBulb** [lihe07/wechat-universal#1]
```shell
export GTK_IM_MODULE=fcitx;
export QT_IM_MODULE=fcitx5;
export XMODIFIERS="@im=fcitx5";  #这里改成fcitx也不行
export SDL_IM_MODULE=fcitx;
# GLFW_IM_MODULE=ibus%   
```

**Comment by lihe07** [comment]
您的环境是什么？Xorg / Wayland，然后用的哪个DE？

**Comment by PureBulb** [comment]
> 您的环境是什么？Xorg / Wayland，然后用的哪个DE？

de是kde,xorg和wayland 都没办法输入,fcitx是fcitx5

**Comment by lihe07** [comment]
AUR里有一个这方面的Workaround了，可以试一下能不能用。如果好用的话，我把这个修改并入。

**Comment by PureBulb** [comment]
> AUR里有一个这方面的Workaround了，可以试一下能不能用。如果好用的话，我把这个修改并入。
ok了，
我根据那个Workaround修改了profile文件 export QT_IM_MODULE=fcitx5 修改成 QT_IM_MODULE=fcitx 就好了

**Comment by PureBulb** [comment]
> AUR里有一个这方面的Workaround了，可以试一下能不能用。如果好用的话，我把这个修改并入。

感谢解答
